# ============================================================
# Stage 1 Test: nodeName with non-existent node (Expected to Fail)
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: stage1-nodename-notfound
  labels:
    test: stage1-fail
spec:
  nodeName: non-existent-node  # Node does not exist
  containers:
  - name: app
    image: quay.io/nginx/nginx-unprivileged:1.27.5-alpine-slim
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
