# ============================================================
# Stage 3 Test: Preferred PodAffinity (Prefer same node as cache)
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: stage3-preferred-podaffinity
  labels:
    test: stage3-score
    component: pod-affinity
spec:
  affinity:
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100  # Prefer same node as cache Pod
        podAffinityTerm:
          labelSelector:
            matchLabels:
              tier: cache
          topologyKey: kubernetes.io/hostname
  containers:
  - name: app
    image: quay.io/nginx/nginx-unprivileged:1.27.5-alpine-slim
    resources:
      requests:
        memory: "16Mi"
        cpu: "10m"
