# ============================================================
# Stage 0: Admission Control - Namespace
# ============================================================
apiVersion: v1
kind: Namespace
metadata:
  name: scheduling-demo
