# ============================================================
# Stage 2 Test: Required NodeAffinity not satisfied (Expected to Fail)
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: stage2-fail-required-affinity
  labels:
    test: stage2-fail
    component: node-affinity
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - zone-x
            - zone-y  # No nodes in zone-x or zone-y (only a, b, c exist)
  containers:
  - name: app
    image: quay.io/nginx/nginx-unprivileged:1.27.5-alpine-slim
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
# Expected: Pending (0/7 nodes match node affinity)
