# ============================================================
# Comprehensive Test: Pod with All Stages Combined
# ============================================================
apiVersion: v1
kind: Pod
metadata:
  name: comprehensive-scheduling-test
  labels:
    test: comprehensive
    app: full-example
spec:
  # ====== Stage 2 Filter (Required) ======

  nodeSelector:
    disktype: ssd  # Filter: Only SSD nodes

  tolerations:
  - key: gpu
    operator: Equal
    value: nvidia
    effect: NoSchedule  # Filter: Allow gpu taint
  - key: maintenance
    operator: Equal
    value: "true"
    effect: PreferNoSchedule  # Stage 3: Scored by TaintToleration plugin

  affinity:
    # Filter: Required NodeAffinity
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - zone-a
            - zone-b

      # ====== Stage 3 Score (Soft Constraints) ======

      # Stage 3: Preferred NodeAffinity
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: zone
            operator: In
            values:
            - zone-a  # Prefer zone-a more

    # Stage 3: Preferred PodAffinity
    podAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        podAffinityTerm:
          labelSelector:
            matchLabels:
              tier: cache
          topologyKey: kubernetes.io/hostname

    # Filter: Required PodAntiAffinity
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            app: full-example
        topologyKey: kubernetes.io/hostname  # Cannot be on same host

  # Filter: TopologySpread (Hard) - Evenly distribute across 3 zones
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app: full-example

  # Filter: Resource Requests
  containers:
  - name: app
    image: quay.io/nginx/nginx-unprivileged:1.27.5-alpine-slim
    resources:
      requests:
        memory: "512Mi"  # Filter: Requires sufficient memory
        cpu: "500m"      # Stage 3: Also affects resource balancing
      limits:
        memory: "1Gi"
        cpu: "1000m"
